package com.marco.beerorderservicenew.domain;

public enum BeerOrderEventEnum {
    NEW,
    VALIDATE_ORDER,
    VALIDATION_PASSED,
    VALIDATION_FAILED,
    ALLOCATE_ORDER,
    ALLOCATED_ON_INVENTORY,
    ALLOCATION_FAILED,
    ALLOCATION_SUCCESS,
    BEER_ORDER_PICKED_UP,
    ALLOCATION_NO_INVENTORY,
    CANCEL_ORDER,
    BEER_ORDER_DELIVERED
}
